server:
  port: 18086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: search-web
#  main:
#    allow-bean-definition-overriding: true
#超时配置
ribbon:
  # Feign请求读取数据超时时间
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时时间，默认1000ms
            timeoutInMilliseconds: 10000
